### ISSUE TITLE
Add Travis CI Integration

### ISSUE THREAD

**Issue by theoretick** [househappy/MapPointMapper-Swift#6]
https://github.com/travis-ci/travis-ci/issues/3216

**Comment by dmiedema** [comment]
This is on hold until Travis supports OS X 10.10 SDK

**Comment by theoretick** [comment]
Beta released http://blog.travis-ci.com/2015-05-26-xcode-63-beta-general-availability/

**Comment by dmiedema** [comment]
:Woo:! Xcode 6_4 is available too. The swift 2.0 branch can't be tested until they support Xcode 7 though
